# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Game_02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Game_02
  pod 'Nama-macOS-lite', '7.3.2'

end
